version: '3.7'

services: 
  service1:
    build: ./service1/.
    image: iwantm/AA:service1
    deploy:
      replicas: 3
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service2:
    build: ./service2/.
    image: iwantm/AA:service2
    deploy:
      replicas: 3
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
