version: '3.7'

services: 
  service1:
    build: /service1/.
    image: 
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service 2:
    build: /service2/.
    image:
    ports:
    - target: 5001
      published: 5001
      protocol: tcp